export const API_ENDPOINT = '/api';

export const BLOCK_TYPES = {
    TEXT: 'TEXT',
    CODE: 'CODE',
    BLOCKQUOTE: 'BLOCKQUOTE',
    IMAGE: 'IMAGE',
    VIDEO: 'VIDEO',
    SUBTITLE: 'SUBTITLE',
    REFERENCE: 'REFERENCE',
    EXPRESSION: 'EXPRESSION',
    LIST: 'LIST',
};