defaults: &defaults
  docker:
    - image: circleci/node:8

version: 2
jobs:
  init:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - n_modules-{{ checksum "package.json" }}
      - run: npm i
      - save_cache:
          paths:
            - node_modules
          key: n_modules-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run build:client
      - run: npm run build:server
      - persist_to_workspace:
          root: .
          paths:
            - public
            - server.bundle.js
  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run deploy
  e2e:
    <<: *defaults
    steps:
      - checkout
      - run: echo "TODO E2E tests"

workflows:
  version: 2
  codelirium:
    jobs:
      - init
      - build:
          requires:
            - init
      - deploy:
          requires:
            - build
          # type: approval
      - e2e:
          requires:
            - deploy