defaults: &defaults
  docker:
    - image: circleci/node:8

version: 2
jobs:
  init:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - n_modules-{{ checksum "package.json" }}
      - run: npm i
      - save_cache:
          paths:
            - node_modules
          key: n_modules-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run build:app
      - run: npm run build:api
      - persist_to_workspace:
          root: .
          paths:
            - build
  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - deploy:
          name: Deploy
          command: |
            echo "iooooooo deploy"

workflows:
  version: 2
  codelirium:
    jobs:
      - init
      - build:
          requires:
            - init
      - deploy:
          type: approval